### ISSUE TITLE
CSP_densenet Input TypeError

### ISSUE THREAD

**Issue by wendywuuu860207** [Knight825/models-pytorch#4]
I try to train csp_densenet() with input size (200, 200, 3) and get type error.
how can I fix it?

`/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)`
 ` return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)`
`Traceback (most recent call last):`
 ` File "train.py", line 185, in <module>
    train(epoch)`
  `File "train.py", line 92, in train
    outputs = net(inputs)`
 ` File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)`
 ` File "/tf/torch_backbones-1.0.0/models/csp_densenet_wen.py", line 94, in forward
    features = self.features(x)`
  `File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)`
 ` File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)`
 ` File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)`
`
  File "/tf/torch_backbones-1.0.0/models/csp_densenet_wen.py", line 43, in forward
    new_feature = layer(*features)
`
`
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
`
`TypeError: forward() takes 2 positional arguments but 3 were given`

**Comment by Knight825** [comment]
Do you use the pytorch >= 1.7? in the code ,denselayer inheritance from torchvision.The denselayer‘s realization is different on different edition。The code is work with torch1.5 and 1.6

**Comment by wendywuuu860207** [comment]
Yes, I use pytorch 1.9, thank you very much for your helping.
I modified __Csp_DenseBlock_ as below and the model work.
```
    def forward(self,x):
        features = [x[:,self.csp_num_features1:,...]]
        features_one = [[]]
        for name,layer in self.named_children():
            if 'denselayer' in name:
                new_feature = layer(*features)
                features_one.append(new_feature)
                features[0] = torch.cat((features[0], new_feature), 1)
        dense = torch.cat(features_one[1:],1)
        if self.transition is not None:
            dense = self.transition(dense)
        return torch.cat([x[:,:self.csp_num_features1,...],dense],1)
```
